version: '3'
services: 
  server:
    build: 
      context: .
      dockerfile: ./docker/nginx/production/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - '80:80'
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    ports:
      - "3000:3000"
    environment:
      # fix
      RAILS_ENV: production
      DB_HOST: ◯◯.△△.ap-northeast-1.rds.amazonaws.com
      DB_USERNAME: ユーザー名
      DB_PASSWORD: パスワード
      DB_DATABASE: データベース名
      TZ: "Asia/Tokyo"
    depends_on:
      - server
