version: '3'
services: 
  server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - '80:80'

  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/unicorn.pid && bundle exec unicorn_rails -c config/unicorn.rb -D -E 'production'"
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo"
    volumes: 
      - .:/app
