version: '3'
services: 
  datastore:
    image: busybox
    volumes:
      - /share
      - ./docker/mysql/volumes:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4020 -b '0.0.0.0'"
    ports:
      - "4020:4020"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes: 
      - .:/app
    volumes_from:
      - datastore
    depends_on:
      - datastore
  db:
    image: mysql:5.7.30
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes_from:
      - datastore
    depends_on:
      - datastore
